
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aerospike-java-client
  name: aerospike-java-client
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aerospike-java-client
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aerospike-java-client
    spec:
      containers:
      - image: ktune/aerospike:java-client
        imagePullPolicy: IfNotPresent
        name: java-client
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
